### ISSUE TITLE
`alembic.run` uses non-existing command

### ISSUE THREAD

**Issue by LeonidMalin** [saritasa-nest/saritasa-python-invocations#14]
Seems like `alembic.run` command uses `python.run_python` command which is not presented in `python` module
![image](https://github.com/saritasa-nest/saritasa-python-invocations/assets/86582591/4ca5d1d3-cbd4-4cc7-bcd9-d935b5910e1b)

**Comment by TheSuperiorStanislav** [comment]
@LeonidMalin should be fixed in this version https://github.com/saritasa-nest/saritasa-python-invocations/releases/tag/0.4.0
